### ISSUE TITLE
2 GPUs less efficient than 1 ?

### ISSUE THREAD

**Issue by deslh** [wouterkool/attention-tsp#5]
I really like this work : learning is pretty quick on small instances.
I have tried to learn vrp100 with 2 GPUs and was surprised to discover that it is slower than with only 1 GPU. As it is my first test with multiple GPUs, I may have done something wrong : is there a parameter that I need to set to run the code on multiple GPU ? 
This test was done with the original sources, on gcloud with pytorch 0.4.1 (some warning for deprecation) . I saw with the nvidia-smi command that both GPUs were busy.  You paper mention a real gain with 2 GPUs ... I'd like to see it as well !
Thanks in advance for any tip !

**Comment by wouterkool** [comment]
Hi, sorry for the very late response as I completely overlooked this issue. It may still be helpful to others as well.

The main reason for using more than 1 GPU is the memory requirement for larger graphs, but it is not necessarily faster by the sequential nature of the algorithm and the overhead (it is difficult to saturate multiple GPUs with PyTorch, especially with a highly dynamic model such as this one). With VRPs, it may work about as fast on just one GPU, but for VRP (compared to TSP) you may risk an out-of-memory error during training as sequence lengths can vary.

For the new version of this work, (which [will be presented at ICLR 2019](https://openreview.net/forum?id=ByxBFsRqYm)) I have used the memory checkpoint functionality to wrap the encoder, allowing larger batch sizes on a single GPU so multi-GPU training is no longer necessary. I will try to update the code somewhere in the coming weeks.

**Comment by chaitjo** [comment]
Would you be updating your code before the paper is presented at ICLR, or after? Looking forward to it.

**Comment by wouterkool** [comment]
@chaitjo I have updated the code. Note that it has undergone a major refactoring. I hope this is helpful to you!
